rename matrix-tests->checkpoint and add more dependencies

diff --git a/.github/workflows/test-and-lint-code.yml b/.github/workflows/test-and-lint-code.yml
--- a/.github/workflows/test-and-lint-code.yml
+++ b/.github/workflows/test-and-lint-code.yml
@@ -370,24 +370,34 @@ jobs:
 
 ################################################################################
 ##                       REQUIRED TEST/LINT COLLECTORS                        ##
-## Jobs in this section collect outputs from matrix-strategy testing jobs,    ##
-## since these are otherwise impossible to capture for branch protection      ##
-## purposes. At the moment, they only need to have each required check as a   ##
-## dependency. Required checks should skip themselves if no relevant files    ##
-## have changed.                                                              ##
+## Jobs in this section collect outputs from testing jobs, since these are    ##
+## otherwise impossible to capture for branch protection purposes.            ##
+## At the moment, they only need to have each required check as a dependency. ##
+## Required checks should skip themselves if no relevant files have changed.  ##                                                           ##
 ##                                                                            ##
 ################################################################################
 
-  matrix_tests:
+  checkpoint:
     if: ${{ always() }}
     runs-on: ubuntu-latest
     needs:
+      # Checkers
       - python_tests_required
+      - python_lint_required
       - sql_tests_required
+      - front_end_checks_required
       - all_be_tests_required
+      # Backend tests
       - python_tests
       - sql_tests
       - api_tests
+      - python_lint
+      # Frontend tests
+      - front_end_format
+      - front_end_lint
+      - front_end_typecheck
+      - front_end_audit
+      - front_end_tests
     steps:
       - name: Check Dependency Results
         run: |
@@ -396,6 +406,7 @@ jobs:
             if [[ "${{ needs.python_tests.result }}" != "success"
               || "${{ needs.sql_tests.result }}" != "success"
               || "${{ needs.api_tests.result }}" != "success"
+              || "${{ needs.python_lint.result }}" != "success"
             ]]; then
               echo "One or more backend tests failed."
               exit 1
@@ -409,11 +420,32 @@ jobs:
               exit 1
             fi
           fi
+          
+          # Check "python_lint_required" conditions
+          if [[ "${{ needs.python_lint_required.outputs.lint_should_run }}" == "true" ]]; then
+            if [[ "${{ needs.python_lint.result }}" != "success" ]]; then
+              echo "python linter failed."
+              exit 1
+            fi  
+          fi
 
           # Check "sql_tests_required" conditions
           if [[ "${{ needs.sql_tests_required.outputs.tests_should_run }}" == "true" ]]; then
             if [[ "${{ needs.sql_tests.result }}" != "success" ]]; then
               echo "SQL tests failed."
+              exit 1
+            fi
+          fi
+
+          # Check "front_end_checks_required" conditions
+          if [[ "${{ needs.front_end_checks_required.outputs.tests_should_run }}" == "true" ]]; then
+            if [[ "${{ needs.front_end_format.result }}" != "success"
+              || "${{ needs.front_end_lint.result }}" != "success"
+              || "${{ needs.front_end_typecheck.result }}" != "success"
+              || "${{ needs.front_end_audit.result }}" != "success"
+              || "${{ needs.front_end_tests.result }}" != "success"
+            ]]; then
+              echo "One or more frontend tests failed."
               exit 1
             fi
           fi
