add condtions

diff --git a/.github/workflows/test-and-lint-code.yml b/.github/workflows/test-and-lint-code.yml
--- a/.github/workflows/test-and-lint-code.yml
+++ b/.github/workflows/test-and-lint-code.yml
@@ -374,9 +374,19 @@ jobs:
 ################################################################################
 
   matrix_tests:
-    if: ${{ always() }}
+    # if: ${{ always() }}
     runs-on: ubuntu-latest
-    needs: [python_tests, sql_tests]
+    needs: [python_tests, sql_tests, api_tests]
     steps:
+      - name: Check Dependency Results
+        run: |
+          # Check if any dependency did not succeed
+          if
+          [ "${{ needs.python_tests.result }}" != "success" ] ||
+          [ "${{ needs.sql_tests.result }}" != "success" ] ||
+          [ "${{ needs.api_tests.result }}" != "success" ]; then
+            echo "One or more dependent tests have failed."
+            exit 1
+          fi
       - name: Report success
         run: echo "All tests succeeded or skipped!"
